#pragma once
#include <ntddk.h>

UNICODE_STRING g_DeviceName = RTL_CONSTANT_STRING(L"\\Device\\ch3rn0byl");
UNICODE_STRING g_SymbolicName = RTL_CONSTANT_STRING(L"\\??\\ch3rn0byl");

#define DRIVER_HOOK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define DRIVER_UNHOOK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define MODULE_POOLTAG 'ch3r'