#pragma once

enum class IrpMajorFunctionCode : unsigned char
{
	_MJ_CREATE = 0,
	_MJ_CREATE_NAMED_PIPE = 1,
	_MJ_CLOSE = 2,
	_MJ_READ = 3,
	_MJ_WRITE = 4,
	_MJ_QUERY_INFORMATION = 5,
	_MJ_SET_INFORMATION = 6,
	_MJ_QUERY_EA = 7,
	_MJ_SET_EA = 8,
	_MJ_FLUSH_BUFFERS = 9,
	_MJ_QUERY_VOLUME_INFORMATION = 0xa,
	_MJ_SET_VOLUME_INFORMATION = 0xb,
	_MJ_DIRECTORY_CONTROL = 0xc,
	_MJ_FILE_SYSTEM_CONTROL = 0xd,
	_MJ_DEVICE_CONTROL = 0xe,
	_MJ_INTERNAL_DEVICE_CONTROL = 0xf,
	_MJ_SHUTDOWN = 0x10,
	_MJ_LOCK_CONTROL = 0x11,
	_MJ_CLEANUP = 0x12,
	_MJ_CREATE_MAILSLOT = 0x13,
	_MJ_QUERY_SECURITY = 0x14,
	_MJ_SET_SECURITY = 0x15,
	_MJ_POWER = 0x16,
	_MJ_SYSTEM_CONTROL = 0x17,
	_MJ_DEVICE_CHANGE = 0x18,
	_MJ_QUERY_QUOTA = 0x19,
	_MJ_SET_QUOTA = 0x1a,
	_MJ_PNP = 0x1b
};